// utils/greetings.ts
import { addUsedGreeting, isGreetingRecentlyUsed } from './greetingCache';

interface Greeting {
  id: string;
  text: string;
}

// Helper to create greetings with unique IDs
let greetingIdCounter = 0;
const createGreeting = (text: string): Greeting => ({
  id: `greeting-${greetingIdCounter++}`,
  text,
});


// More diverse greetings
const holidays: Record<string, Greeting[]> = {
  '01-01': [
    createGreeting("🎉 Happy New Year! May your watchlist be ever-growing."),
    createGreeting("✨ New year, new anime to discover. Let's get started!"),
    createGreeting("🎊 Cheers to a year filled with epic stories and thrilling adventures!"),
    createGreeting("🥂 A fresh start for your anime journey. What will you conquer first?"),
    createGreeting("🎆 Happy New Year! Time to set some anime goals."),
    createGreeting("🌟 Wishing you a year of fantastic anime and memorable moments."),
    createGreeting("🥳 Another year, another season of must-watch anime!"),
    createGreeting("💖 May your New Year be filled with joy and your favorite waifus/husbandos."),
    createGreeting("📆 Kick off the year with a bang, or a brilliant new series!"),
    createGreeting("🔮 What anime fortunes will this year bring?"),
  ],
  '02-14': [
    createGreeting("❤️ Happy Valentine's Day! Hope you love what you're watching."),
    createGreeting("🥰 Found a new anime to fall in love with today?"),
    createGreeting("💘 May your day be filled with love and your favorite anime characters!"),
    createGreeting("🌹 Spend Valentine's Day with your true anime waifu/husbando!"),
    createGreeting("💞 Love is in the air... and so is the scent of new episodes."),
    createGreeting("🍫 Sweeter than chocolate: finding that perfect romantic anime."),
    createGreeting("💌 Sending you good vibes and great anime recommendations this Valentine's!"),
    createGreeting("💖 Dive into a heartwarming romance or a passionate shonen battle!"),
  ],
  '03-08': [ // International Women's Day
    createGreeting("💪 Happy International Women's Day! Celebrate strong anime heroines."),
    createGreeting("👑 To all the queens and warriors in anime (and real life)!"),
  ],
  '03-17': [ // St. Patrick's Day
    createGreeting("🍀 Happy St. Patrick's Day! May your day be full of luck and great anime."),
    createGreeting("💚 Feeling lucky? Time to find a hidden gem in your backlog!"),
    createGreeting("🌈 Chasing rainbows and epic anime plot twists!"),
  ],
  '04-01': [ // April Fool's Day
    createGreeting(" fooling yourself? You know you want to watch another episode!"),
    createGreeting("🃏 Happy April Fool's! No jokes, just good anime today."),
    createGreeting("😂 Don't be fooled by fake spoilers, only trust the true anime path!"),
    createGreeting("🤡 Pranks are fun, but watching anime is serious business."),
  ],
  '04-22': [ // Earth Day
    createGreeting("🌎 Happy Earth Day! Let's protect our world, just like our anime heroes."),
    createGreeting("🌱 Take a break, enjoy nature, then get back to some wholesome anime!"),
  ],
  '05-04': [ // Star Wars Day (May the 4th) - if we want pop culture references
    createGreeting("🌟 May the 4th be with you! What's your favorite space opera anime?"),
    createGreeting("🌌 Explore a galaxy far, far away... or just your watchlist!"),
    createGreeting("🚀 Blast off into an intergalactic anime adventure!"),
  ],
  '05-12': [ // Mother's Day (second Sunday in May, arbitrary date for now, need proper calculation)
    createGreeting("💐 Happy Mother's Day! Appreciate the strong moms in anime and in life."),
    createGreeting("👩‍👧‍👦 Moms make the world go 'round, and sometimes, they even introduce us to anime!"),
  ],
  '06-16': [ // Father's Day (third Sunday in June, arbitrary date for now)
    createGreeting("👔 Happy Father's Day! Shoutout to the coolest anime dads."),
    createGreeting("🦸‍♂️ Celebrating the unsung heroes and father figures of the anime world!"),
  ],
  '10-31': [
    createGreeting("🎃 Happy Halloween! Time for some spooky or supernatural anime."),
    createGreeting("👻 Don't get too spooked by your watchlist tonight!"),
    createGreeting("🌙 The perfect night for a chilling psychological thriller anime."),
    createGreeting("🍬 Trick or treat yo'self to some fantastic episodes!"),
    createGreeting("🕷️ Beware of jump scares... and plot twists!"),
    createGreeting("🧟‍♂️ Get into the spirit with some monstrously good anime!"),
    createGreeting("🕯️ Light a candle and immerse yourself in a dark fantasy."),
    createGreeting("🕸️ Spooky season is prime time for horror anime!"),
  ],
  '11-4-4': [ // Represents the 4th Thursday of November for US Thanksgiving
    createGreeting("🦃 Happy Thanksgiving! Thankful for all the amazing anime out there."),
    createGreeting("🍂 Hope you're having a cozy Thanksgiving, maybe with some anime?"),
    createGreeting("🧡 Gather with loved ones and share the joy of anime (or just watch alone, we get it)."),
    createGreeting("🥧 After the feast, the ultimate anime binge begins!"),
    createGreeting("🍁 Feeling grateful for good food, good company, and great shows."),
    createGreeting("🍽️ Feast, then binge-watch. It's the Thanksgiving way."),
  ],
  '12-24': [
    createGreeting("🌃 'Twas the night before Christmas... perfect for an anime marathon!"),
    createGreeting("🎄 Getting in some last-minute watching before the big day?"),
    createGreeting("🌟 Wishing you a magical Christmas Eve filled with anticipation and anime."),
    createGreeting("🎁 One more sleep until gifts... and uninterrupted anime time!"),
    createGreeting("🎅 The calm before the festive storm, ideal for an episode or two."),
    createGreeting("✨ May your Christmas Eve be merry and bright with anime lights!"),
    createGreeting("🔔 Dreaming of a white Christmas... and a full watchlist."),
  ],
  '12-25': [
    createGreeting("🎁 Merry Christmas! Hope you got some great anime to watch."),
    createGreeting("🎅 Wishing you a very Merry Christmas and a happy watchlist."),
    createGreeting("☃️ May your day be merry, bright, and full of your favorite holiday anime specials."),
    createGreeting("✨ Unwrap new stories and enjoy the festive cheer!"),
    createGreeting("🎄 Merry Christmas! What new anime will you discover today?"),
    createGreeting("🌟 Sharing the joy of anime with friends and family (or just yourself!)."),
    createGreeting("🕊️ Peace on Earth, and endless episodes in your queue."),
    createGreeting("🎁 May your day be filled with warmth, wonder, and exciting anime reveals!"),
  ],
  '12-31': [ // New Year's Eve
    createGreeting("🥳 Happy New Year's Eve! Reflect on your year of anime achievements."),
    createGreeting("🎆 Counting down to a new year of epic anime moments!"),
    createGreeting("🥂 One last binge before the year ends!"),
    createGreeting("🕛 Make your last watch of the year count!"),
    createGreeting("🎊 Celebrating all the incredible anime you watched this year!"),
    createGreeting("✨ Looking back at your favorite anime memories of the year."),
    createGreeting("🗓️ The final countdown for your watchlist!"),
    createGreeting("🍾 Raise a glass to another fantastic year of anime!"),
  ],
};

const months: Greeting[][] = [
  // January (Approx. 60 greetings)
  [
    createGreeting("🚀 Kicking off the new year with some great stories."),
    createGreeting("❄️ A perfect month to start a new series."),
    createGreeting("🌨️ January chill calls for warm blankets and hot takes on anime."),
    createGreeting("🧊 Embrace the cold, immerse in a new world."),
    createGreeting("✨ New year, new watchlist goals. What's first?"),
    createGreeting("🥂 Cheers to 12 months of epic anime journeys!"),
    createGreeting("📝 Time to plan your anime binges for the year ahead."),
    createGreeting("🥶 Winter has truly set in. Perfect for cozy anime nights."),
    createGreeting("☃️ Build a snow-anime-man! Or just watch anime."),
    createGreeting("🗓️ Fresh start, fresh episodes. The cycle continues."),
    createGreeting("📚 Catching up on all those winter season releases."),
    createGreeting("🌟 May your January be filled with magical moments."),
    createGreeting("🌌 Dive deep into worlds unknown this chilly month."),
    createGreeting("🏞️ Starting new arcs, just like the year itself."),
    createGreeting("🌬️ Brisk air calls for captivating stories."),
    createGreeting("☕ Hot drinks and even hotter anime plots."),
    createGreeting("🖥️ Your ultimate anime hub, ready for the new year."),
    createGreeting("📆 January: The month of new beginnings and hidden gems."),
    createGreeting("📈 What anime will climb to the top of your list this month?"),
    createGreeting("💡 Discovering the next big thing in anime."),
    createGreeting("🌨️ Snowy days are best spent with a compelling narrative."),
    createGreeting("🧊 Let your imagination melt the winter ice."),
    createGreeting("🎉 January is for fresh starts and fantastic anime!"),
    createGreeting("💖 May your watchlist be as full as your heart this month."),
    createGreeting("✨ Sparking new interests with every episode."),
    createGreeting("🌟 Wishing you a starry January, filled with anime wonders."),
    createGreeting("📚 Get ready to devour some literary adaptations."),
    createGreeting("🥶 Conquer the cold with courage, just like your heroes."),
    createGreeting("🗓️ The first chapter of your anime year."),
    createGreeting("🎬 Premieres are hitting hard this winter season!"),
    createGreeting("🎮 Level up your viewing experience this January."),
    createGreeting("📝 Setting new personal bests for episodes watched."),
    createGreeting("🌱 Growth and new beginnings, even in the coldest month."),
    createGreeting("🎁 Treat yourself to some well-deserved anime time."),
    createGreeting("🕯️ Cozy up by the screen and let the stories unfold."),
    createGreeting("🗺️ Charting new anime territories this month."),
    createGreeting("🧭 Where will your anime journey take you next?"),
    createGreeting("🎇 A month for reflection and new anime resolutions."),
    createGreeting("🗓️ January, the quiet prelude to a year of adventure."),
    createGreeting("🧊 Break the ice with an action-packed series!"),
    createGreeting("🌟 Feel the magic of winter through animated worlds."),
    createGreeting("📚 Your mental library of anime is expanding!"),
    createGreeting("☕ Sip, watch, and repeat through the long nights."),
    createGreeting("🖥️ The perfect screen to light up dark winter evenings."),
    createGreeting("📈 Reaching new heights on your anime journey."),
    createGreeting("💡 Bright ideas and even brighter animation!"),
    createGreeting("🌨️ Let the animation snow fall gently on your screen."),
    createGreeting("🧊 Don't let the chill deter your quest for great anime."),
    createGreeting("🎉 Celebrate every discovery, big or small!"),
    createGreeting("💖 A little love for your favorite characters this month."),
    createGreeting("✨ What hidden powers will your heroes unlock next?"),
    createGreeting("🌟 Shining bright with every new episode you watch."),
    createGreeting("📚 Expand your mind with unique anime concepts."),
    createGreeting("🥶 Find warmth in the bonds of anime friendships."),
    createGreeting("🗓️ A new page turns in your anime journal."),
    createGreeting("🎬 The show must go on, even in winter!"),
    createGreeting("🎮 Ready player one, your anime awaits!"),
    createGreeting("📝 Jot down your thoughts on new releases."),
    createGreeting("🌱 Cultivating a superb watchlist for the year."),
    createGreeting("🎁 Unwrapping the gift of endless entertainment."),
    createGreeting("🕯️ Creating a serene atmosphere for serious viewing."),
    createGreeting("🗺️ Journey through fantastical lands from your couch."),
  ],
  // February (Approx. 60 greetings)
  [
    createGreeting("⏳ Short month, long watchlist. Let's make it count."),
    createGreeting("💖 Finding a new show to love this February?"),
    createGreeting("💘 Love is in the air, and so are new episodes!"),
    createGreeting("🥶 February might be cold, but these anime are fire!"),
    createGreeting("💌 Spreading some anime love this month."),
    createGreeting("🌹 Will your next watch be a sweet romance or an epic tragedy?"),
    createGreeting("📆 The shortest month, but full of anime potential."),
    createGreeting("🍫 Treat yourself to a binge-watching session."),
    createGreeting("🕯️ Cozy up with a heartwarming slice-of-life."),
    createGreeting("✨ Sparking joy with every new discovery."),
    createGreeting("❄️ February flurries mean more time indoors for anime."),
    createGreeting("📚 Diving into some captivating winter narratives."),
    createGreeting("💖 Feel the love (and the action) in your favorite series."),
    createGreeting(" Cupid's arrow points to your next favorite anime!"),
    createGreeting("🌨️ Weather outside is frightful, anime inside is delightful."),
    createGreeting("🎭 Prepare for drama, comedy, and everything in between."),
    createGreeting("🗓️ Making every day count with fantastic stories."),
    createGreeting("🥂 Toasting to your growing anime collection."),
    createGreeting("🌟 February nights are perfect for starry-eyed adventures."),
    createGreeting("🌌 Lost in translation? Never in anime!"),
    createGreeting("🚀 Blast through your backlog this month."),
    createGreeting("📝 What's on your 'must-watch' list for February?"),
    createGreeting("🌱 Glimmers of spring, and new anime announcements!"),
    createGreeting("🎁 A little gift of anime to yourself today."),
    createGreeting("🗺️ Charting new emotional territories with character arcs."),
    createGreeting("🧭 Following your heart (and the anime schedule)."),
    createGreeting("🎇 A month of hidden delights and unexpected gems."),
    createGreeting("🗓️ February, a bridge between winter's end and spring's promise."),
    createGreeting("🧊 Chilling adventures await in the frosty air."),
    createGreeting("🌟 Let anime light up your shortest month."),
    createGreeting("📚 Expand your horizons with diverse genres."),
    createGreeting("☕ A warm beverage and a compelling plot, perfect for February."),
    createGreeting("🖥️ Your personal portal to animated excellence."),
    createGreeting("📈 Growing your anime wisdom, one episode at a time."),
    createGreeting("💡 Brilliant animation shining through the winter gloom."),
    createGreeting("🌨️ Snuggle up and let the stories sweep you away."),
    createGreeting("🧊 Breaking free from the mundane with fantastical escapes."),
    createGreeting("🎉 Every completed series is a small victory!"),
    createGreeting("💖 Embracing the emotional depth of animated masterpieces."),
    createGreeting("✨ The magic of anime is always within reach."),
    createGreeting("🌟 A constellation of characters waiting to be discovered."),
    createGreeting("📚 Explore new narratives and artistic styles."),
    createGreeting("🥶 Find comfort in the familiar and excitement in the new."),
    createGreeting("🗓️ Mark your calendars for upcoming releases!"),
    createGreeting("🎬 The curtain rises on many new adventures."),
    createGreeting("🎮 Level up your leisure time with immersive worlds."),
    createGreeting("📝 Documenting your thoughts on current obsessions."),
    createGreeting("🌱 Witnessing character growth like never before."),
    createGreeting("🎁 The joy of discovering a truly great show."),
    createGreeting("🕯️ Setting the mood for some serious screen time."),
    createGreeting("🗺️ Navigating complex plots with ease and enjoyment."),
    createGreeting("🧭 Finding your way through epic sagas."),
    createGreeting("🎇 A burst of color and creativity this month."),
    createGreeting("🗓️ February: small but mighty in anime potential."),
    createGreeting("🧊 Defrost your mind with thrilling mysteries."),
    createGreeting("🌟 Your guide to the best stories under the winter sky."),
    createGreeting("📚 Read up on the manga, then watch the adaptation!"),
    createGreeting("☕ The perfect companion for quiet evenings."),
    createGreeting("🖥️ Upgrading your viewing experience with every choice."),
  ],
  // March (Approx. 60 greetings)
  [
    createGreeting("🌱 Spring is coming! Time for some fresh new anime."),
    createGreeting("🍀 Marching through your watchlist like a pro."),
    createGreeting("☔️ Spring showers bring blooming watchlists."),
    createGreeting("💨 Wind of change, or just a new anime season?"),
    createGreeting("🌷 New anime buds are starting to blossom."),
    createGreeting("💚 Happy St. Patrick's Day (if applicable)! Enjoy a green anime!"),
    createGreeting("🗓️ The vernal equinox means longer days for watching!"),
    createGreeting("🦋 Witnessing transformations, both in nature and character arcs."),
    createGreeting("🧺 Planning a spring anime picnic (indoors, of course)."),
    createGreeting("✨ Spring cleaning your backlog? Or just adding more?"),
    createGreeting("🌧️ Don't let the rain stop your anime parade."),
    createGreeting("🌸 Cherry blossoms, and fresh anime premieres."),
    createGreeting("🚀 Launching into spring with high hopes and new episodes."),
    createGreeting("📚 Time to shed the winter slump and find something new."),
    createGreeting("🌱 Witnessing growth and fresh perspectives."),
    createGreeting("📈 Marching forward with your anime progress."),
    createGreeting("💡 Bright new stories for the brighter days."),
    createGreeting("🥳 Spring into action with your favorite genres."),
    createGreeting("💖 Feel the refreshing energy of new beginnings."),
    createGreeting("🌟 March's magic, unfolding one episode at a time."),
    createGreeting("🌌 Explore vibrant new worlds as nature awakens."),
    createGreeting("🌬️ Catching the breeze of new anime trends."),
    createGreeting("☕ Trading hot chocolate for iced coffee and anime."),
    createGreeting("🖥️ Your ultimate spring anime viewing station."),
    createGreeting("📆 March: a month of transitions and thrilling new arcs."),
    createGreeting("📈 What hidden gems will spring reveal?"),
    createGreeting("💡 Illuminating your mind with captivating plots."),
    createGreeting("🌧️ Find comfort in captivating indoor adventures."),
    createGreeting("🌸 Celebrate the beauty of anime art styles."),
    createGreeting("🚀 Prepare for an exciting new season!"),
    createGreeting("📚 Deep dive into intricate plots and character studies."),
    createGreeting("🌱 Every new episode is a fresh leaf on your watchlist tree."),
    createGreeting("🎁 A little treat for your inner otaku."),
    createGreeting("🕯️ Brightening up your evenings with compelling narratives."),
    createGreeting("🗺️ Navigating the currents of the anime world."),
    createGreeting("🧭 Setting sail for new anime horizons."),
    createGreeting("🎇 A month of vibrant discoveries and thrilling twists."),
    createGreeting("🗓️ March: the canvas for your next anime masterpiece."),
    createGreeting("☔️ Embrace the coziness of indoor viewing during spring showers."),
    createGreeting("🌟 Let anime fill your days with wonder."),
    createGreeting("📚 Curate your perfect spring anime lineup."),
    createGreeting("☕ Enjoying the transition with a comforting watch."),
    createGreeting("🖥️ The gateway to endless entertainment this spring."),
    createGreeting("📈 Surpassing your own anime expectations."),
    createGreeting("💡 Unleashing your inner critic on new releases."),
    createGreeting("🥳 Every binge-watch is a celebration!"),
    createGreeting("💖 Fall in love with new characters and worlds."),
    createGreeting("✨ The spark of inspiration from unique storytelling."),
    createGreeting("🌟 A sparkling selection of shows awaits."),
    createGreeting("📚 Delve into the lore and world-building."),
    createGreeting("💨 Riding the winds of hype for upcoming shows."),
    createGreeting("🗓️ The start of something beautiful this March."),
    createGreeting("🎬 Get ready for some fantastic seasonal anime!"),
    createGreeting("🎮 Powering through quests and episodes."),
    createGreeting("📝 Keeping track of your favorites and new finds."),
    createGreeting("🌱 Nurturing your passion for anime."),
    createGreeting("🎁 The gift of escapism, always available."),
    createGreeting("🕯️ Adding a touch of magic to your viewing sessions."),
    createGreeting("🗺️ Exploring vast narratives, one episode at a time."),
  ],
  // April (Approx. 60 greetings)
  [
    createGreeting("🌦️ April showers bring... more time for anime marathons!"),
    createGreeting("🌸 New season of anime, new possibilities."),
    createGreeting("🌧️ Don't let the rain stop your anime parade."),
    createGreeting("🐰 Spring has sprung, time for some fresh content."),
    createGreeting("🌱 April: The month of growth and blooming watchlists."),
    createGreeting("🐣 Hope your spring is full of delightful surprises!"),
    createGreeting("🗓️ Longer days means more opportunities for screen time."),
    createGreeting("🦋 Witnessing character evolutions and vibrant art."),
    createGreeting("🧺 A perfect day for a cozy indoors anime binge."),
    createGreeting("✨ April magic, one episode at a time."),
    createGreeting("☔️ Rainy days are the best for deep dives into series."),
    createGreeting("🌸 Cherry blossom season is prime for poignant stories."),
    createGreeting("🚀 Launching into new anime experiences this month."),
    createGreeting("📚 Unearthing forgotten gems in your backlog."),
    createGreeting("🌱 Cultivating your ideal spring watchlist."),
    createGreeting("📈 April is for making progress on those long series."),
    createGreeting("💡 Bright ideas for your next binge-watch."),
    createGreeting("🥳 Celebrate the new anime season with joy!"),
    createGreeting("💖 Feel the refreshing energy of spring anime."),
    createGreeting("🌟 April showers bring anime flowers!"),
    createGreeting("🌌 Explore new dimensions and fantastical realms."),
    createGreeting("🌬️ Let the winds of new narratives carry you away."),
    createGreeting("☕ Sipping on something cool while watching hot new releases."),
    createGreeting("🖥️ Your personalized portal to springtime animation."),
    createGreeting("📆 April: a month of renewal and thrilling twists."),
    createGreeting("📈 What captivating stories will April unveil?"),
    createGreeting("💡 Illuminating your evenings with compelling plots."),
    createGreeting("🌧️ Finding comfort in captivating indoor escapades."),
    createGreeting("🌸 Adorn your screen with beautiful anime visuals."),
    createGreeting("🚀 Prepare for an exhilarating new season!"),
    createGreeting("📚 Deep dive into rich narratives and character growth."),
    createGreeting("🌱 Every episode is a step into a vibrant world."),
    createGreeting("🎁 A little treat of anime for your soul."),
    createGreeting("🕯️ Adding a gentle glow to your viewing sessions."),
    createGreeting("🗺️ Navigating the evolving landscape of anime."),
    createGreeting("🧭 Setting a course for new narrative adventures."),
    createGreeting("🎇 A month of sparkling content and exciting plots."),
    createGreeting("🗓️ April: the canvas for your next anime journey."),
    createGreeting("☔️ Enjoying the tranquility of a rainy day anime marathon."),
    createGreeting("🌟 Let anime brighten your spring days."),
    createGreeting("📚 Expanding your appreciation for animation."),
    createGreeting("☕ The perfect blend of comfort and excitement."),
    createGreeting("🖥️ The ultimate hub for your springtime viewing."),
    createGreeting("📈 Achieving new milestones on your watchlist."),
    createGreeting("💡 Unleash your imagination with creative storytelling."),
    createGreeting("🥳 Every new episode is a cause for celebration!"),
    createGreeting("💖 Discovering new crushes and beloved characters."),
    createGreeting("✨ The magic of a good story never fades."),
    createGreeting("🌟 A dazzling array of shows awaits your attention."),
    createGreeting("📚 Immerse yourself in intricate world-building."),
    createGreeting("💨 Riding the wave of new seasonal hits."),
    createGreeting("🗓️ The start of something fantastic this April."),
    createGreeting("🎬 Get ready for some groundbreaking anime releases!"),
    createGreeting("🎮 Embark on epic quests from the comfort of your home."),
    createGreeting("📝 Documenting your favorite moments and quotes."),
    createGreeting("🌱 Nurturing your passion for diverse anime."),
    createGreeting("🎁 The endless joy of discovering new narratives."),
    createGreeting("🕯️ Crafting the perfect atmosphere for anime viewing."),
    createGreeting("🗺️ Traverse vast storyscapes with ease and delight."),
  ],
  // May (Approx. 60 greetings)
  [
    createGreeting("🌷 May your watchlist be as bright as the spring flowers."),
    createGreeting("☀️ The weather is warming up, and so are the new anime releases."),
    createGreeting("💐 Flowers are blooming, and so is your potential for new favorite shows."),
    createGreeting("🐝 Buzzing with excitement for what's next on your list?"),
    createGreeting("🌱 May: A month of vibrant growth and exciting anime."),
    createGreeting("🗓️ Long days, perfect for long anime sessions."),
    createGreeting("🦋 Witnessing beautiful transformations in characters and plots."),
    createGreeting("🧺 Time for a sunny outdoor anime viewing (if screen allows!)."),
    createGreeting("✨ May's magic, unfolding one episode at a time."),
    createGreeting("🌸 Enjoy the peak of spring with captivating narratives."),
    createGreeting("🚀 Launching into pre-summer anime fun!"),
    createGreeting("📚 Dive into new stories before the summer rush."),
    createGreeting("🌱 Cultivating a superb spring-to-summer watchlist."),
    createGreeting("📈 Making steady progress on your anime goals."),
    createGreeting("💡 Bright new adventures for the brighter days."),
    createGreeting("🥳 Celebrate the beauty of anime this month!"),
    createGreeting("💖 Feel the gentle warmth of May with a heartwarming series."),
    createGreeting("🌟 May the anime force be with you!"),
    createGreeting("🌌 Explore new worlds as nature bursts into life."),
    createGreeting("🌬️ Catching the gentle breeze of fresh anime content."),
    createGreeting("☕ Switching to iced tea for your viewing pleasure."),
    createGreeting("🖥️ Your ultimate spring-to-summer anime hub."),
    createGreeting("📆 May: a month of natural beauty and narrative depth."),
    createGreeting("📈 What captivating plots will May reveal?"),
    createGreeting("💡 Illuminating your evenings with compelling character arcs."),
    createGreeting("☀️ Soaking in the sunshine, and the stellar animation."),
    createGreeting("🌸 Adorn your screen with lush anime visuals."),
    createGreeting("🚀 Prepare for exciting lead-ups to summer releases!"),
    createGreeting("📚 Deep dive into rich narratives and complex themes."),
    createGreeting("🌱 Every episode is a journey through a vibrant world."),
    createGreeting("🎁 A little treat of animation for your mental well-being."),
    createGreeting("🕯️ Adding a soft glow to your relaxing viewing sessions."),
    createGreeting("🗺️ Navigating the ever-evolving anime landscape."),
    createGreeting("🧭 Setting a course for new narrative discoveries."),
    createGreeting("🎇 A month of sparkling content and emotional depth."),
    createGreeting("🗓️ May: the canvas for your next great anime memory."),
    createGreeting("🌷 Enjoying the serenity of a beautiful spring day with anime."),
    createGreeting("🌟 Let anime fill your days with wonder and excitement."),
    createGreeting("📚 Expanding your appreciation for diverse storytelling."),
    createGreeting("☕ The perfect blend of relaxation and thrilling action."),
    createGreeting("🖥️ The ultimate gateway to springtime entertainment."),
    createGreeting("📈 Achieving new personal bests on your watchlist."),
    createGreeting("💡 Unleash your creativity with imaginative anime concepts."),
    createGreeting("🥳 Every new series is a cause for celebration!"),
    createGreeting("💖 Discovering new ships and OTPs this month."),
    createGreeting("✨ The magic of a well-told story resonates."),
    createGreeting("🌟 A dazzling array of shows awaits your undivided attention."),
    createGreeting("📚 Immerse yourself in intricate backstories and lore."),
    createGreeting("💨 Riding the wave of anticipation for upcoming hits."),
    createGreeting("🗓️ The start of something fantastic this May."),
    createGreeting("🎬 Get ready for some visually stunning anime premieres!"),
    createGreeting("🎮 Embark on thrilling quests from your favorite seat."),
    createGreeting("📝 Documenting your thoughts on current favorites."),
    createGreeting("🌱 Nurturing your inner otaku with quality content."),
    createGreeting("🎁 The endless joy of finding that perfect series."),
    createGreeting("🕯️ Crafting the ideal atmosphere for a deep dive."),
    createGreeting("🗺️ Traverse vast fictional worlds with ease and joy."),
  ],
  // June (Approx. 60 greetings)
  [
    createGreeting("🏖️ Summer's here! Perfect time for a cool story."),
    createGreeting("😎 Longer days mean more time for anime. It's just science."),
    createGreeting("🍉 Beat the heat with some chill anime vibes."),
    createGreeting("☀️ Summer adventures await, on-screen and off!"),
    createGreeting("🌊 Dive into some refreshing new series."),
    createGreeting("🍦 Sweet treats and even sweeter anime plots."),
    createGreeting("🗓️ The longest days of the year are here. More watch time!"),
    createGreeting("🌸 Summer anime season is officially in full swing!"),
    createGreeting("🏖️ Planning your ultimate summer anime watch list?"),
    createGreeting("✨ June magic, one episode at a time."),
    createGreeting("☀️ Soaking up the sun, and the stellar animation."),
    createGreeting("🚀 Launching into epic summer binges!"),
    createGreeting("📚 Discovering lighthearted summer fun or intense thrillers."),
    createGreeting("🌱 Cultivating your perfect summer watchlist."),
    createGreeting("📈 Making hot progress on your anime goals."),
    createGreeting("💡 Bright new stories for the brightest days."),
    createGreeting("🥳 Celebrate the start of summer with your favorite shows!"),
    createGreeting("💖 Feel the refreshing energy of summer anime."),
    createGreeting("🌟 June nights are perfect for starry-eyed adventures."),
    createGreeting("🌌 Explore new worlds under the summer sky."),
    createGreeting("🌬️ Catching the gentle breeze of fresh anime content."),
    createGreeting("☕ Switching to iced coffee or cold brew for your viewing pleasure."),
    createGreeting("🖥️ Your ultimate summer anime hub is ready."),
    createGreeting("📆 June: a month of bright days and deep narratives."),
    createGreeting("📈 What captivating stories will June reveal?"),
    createGreeting("💡 Illuminating your evenings with compelling character arcs."),
    createGreeting("😎 Enjoying the warmth, and the captivating stories."),
    createGreeting("🌸 Adorn your screen with vibrant anime visuals."),
    createGreeting("🚀 Prepare for an exhilarating summer season!"),
    createGreeting("📚 Deep dive into rich narratives and complex themes."),
    createGreeting("🌱 Every episode is a journey through a vibrant world."),
    createGreeting("🎁 A little treat of animation for your mental well-being."),
    createGreeting("🕯️ Adding a soft glow to your relaxing viewing sessions."),
    createGreeting("🗺️ Navigating the ever-evolving anime landscape."),
    createGreeting("🧭 Setting a course for new narrative discoveries."),
    createGreeting("🎇 A month of sparkling content and emotional depth."),
    createGreeting("🗓️ June: the canvas for your next great anime memory."),
    createGreeting("🌊 Splashing into refreshing new anime experiences."),
    createGreeting("🌟 Let anime fill your summer days with wonder and excitement."),
    createGreeting("📚 Expanding your appreciation for diverse storytelling."),
    createGreeting("☕ The perfect blend of relaxation and thrilling action."),
    createGreeting("🖥️ The ultimate gateway to summer entertainment."),
    createGreeting("📈 Achieving new personal bests on your watchlist."),
    createGreeting("💡 Unleash your creativity with imaginative anime concepts."),
    createGreeting("🥳 Every new series is a cause for celebration!"),
    createGreeting("💖 Discovering new ships and OTPs this month."),
    createGreeting("✨ The magic of a well-told story resonates."),
    createGreeting("🌟 A dazzling array of shows awaits your undivided attention."),
    createGreeting("📚 Immerse yourself in intricate backstories and lore."),
    createGreeting("💨 Riding the wave of anticipation for upcoming hits."),
    createGreeting("🗓️ The start of something fantastic this June."),
    createGreeting("🎬 Get ready for some visually stunning anime premieres!"),
    createGreeting("🎮 Embark on thrilling quests from your favorite seat."),
    createGreeting("📝 Documenting your thoughts on current favorites."),
    createGreeting("🌱 Nurturing your inner otaku with quality content."),
    createGreeting("🎁 The endless joy of finding that perfect series."),
    createGreeting("🕯️ Crafting the ideal atmosphere for a deep dive."),
    createGreeting("🗺️ Traverse vast fictional worlds with ease and joy."),
  ],
  // July (Approx. 60 greetings)
  [
    createGreeting("🎆 Hope your summer is as epic as your favorite anime."),
    createGreeting("🍉 Staying cool with some hot new episodes?"),
    createGreeting("🎇 Fireworks and fantastic anime – a perfect match."),
    createGreeting("🔥 Heating up your summer with action-packed series."),
    createGreeting("🍹 Sipping on a cool drink while catching up on your watchlist."),
    createGreeting("☀️ The sun is high, and so is your anime enthusiasm!"),
    createGreeting("🌊 Dive into new stories or re-watch summer classics."),
    createGreeting("🗓️ July: The heart of summer and peak anime season."),
    createGreeting("😎 Embrace the long days and thrilling nights of anime."),
    createGreeting("✨ July magic, one episode at a time."),
    createGreeting("🚀 Launching into even more anime adventures!"),
    createGreeting("📚 Finding that perfect beach-read anime."),
    createGreeting("🌱 Growing your watchlist with every passing day."),
    createGreeting("📈 Making sizzling progress on your anime goals."),
    createGreeting("💡 Bright new narratives for the brightest month."),
    createGreeting("🥳 Celebrate summer with endless anime fun!"),
    createGreeting("💖 Feel the vibrant energy of July anime releases."),
    createGreeting("🌟 July nights are perfect for stargazing and screen time."),
    createGreeting("🌌 Explore new galaxies and dimensions from your couch."),
    createGreeting("🌬️ Catching the refreshing breeze of new anime trends."),
    createGreeting("☕ Keeping cool with chilled beverages and captivating plots."),
    createGreeting("🖥️ Your ultimate summer anime command center."),
    createGreeting("📆 July: a month of dazzling stories and unforgettable arcs."),
    createGreeting("📈 What exciting plots will July reveal?"),
    createGreeting("💡 Illuminating your evenings with compelling character journeys."),
    createGreeting("😎 Enjoying the summer warmth and stunning animation."),
    createGreeting("🌸 Adorn your screen with brilliant anime visuals."),
    createGreeting("🚀 Prepare for an even more exhilarating summer season!"),
    createGreeting("📚 Deep dive into intricate narratives and complex themes."),
    createGreeting("🌱 Every episode is a gateway to a vibrant world."),
    createGreeting("🎁 A little treat of animation for your adventurous spirit."),
    createGreeting("🕯️ Adding a soft glow to your relaxing viewing sessions."),
    createGreeting("🗺️ Navigating the ever-expanding anime universe."),
    createGreeting("🧭 Setting a course for new narrative frontiers."),
    createGreeting("🎇 A month of explosive content and emotional depth."),
    createGreeting("🗓️ July: the canvas for your next great anime memory."),
    createGreeting("🌊 Splashing into even more refreshing anime experiences."),
    createGreeting("🌟 Let anime fill your summer days with wonder and excitement."),
    createGreeting("📚 Expanding your appreciation for diverse storytelling."),
    createGreeting("☕ The perfect blend of summer relaxation and thrilling action."),
    createGreeting("🖥️ The ultimate gateway to summer entertainment."),
    createGreeting("📈 Achieving new personal bests on your watchlist."),
    createGreeting("💡 Unleash your creativity with imaginative anime concepts."),
    createGreeting("🥳 Every new series is a cause for celebration!"),
    createGreeting("💖 Discovering new ships and OTPs this month."),
    createGreeting("✨ The magic of a well-told story resonates."),
    createGreeting("🌟 A dazzling array of shows awaits your undivided attention."),
    createGreeting("📚 Immerse yourself in intricate backstories and lore."),
    createGreeting("💨 Riding the wave of anticipation for upcoming hits."),
    createGreeting("🗓️ The start of something fantastic this July."),
    createGreeting("🎬 Get ready for some visually stunning anime premieres!"),
    createGreeting("🎮 Embark on thrilling quests from your favorite seat."),
    createGreeting("📝 Documenting your thoughts on current favorites."),
    createGreeting("🌱 Nurturing your inner otaku with quality content."),
    createGreeting("🎁 The endless joy of finding that perfect series."),
    createGreeting("🕯️ Crafting the ideal atmosphere for a deep dive."),
    createGreeting("🗺️ Traverse vast fictional worlds with ease and joy."),
  ],
  // August (Approx. 60 greetings)
  [
    createGreeting("🍦 The dog days of summer are perfect for chilling with anime."),
    createGreeting("🥵 Soaking up the last bit of summer with a good series?"),
    createGreeting("📚 Back to school season, but never too busy for anime."),
    createGreeting("🌅 Summer nights and endless anime possibilities."),
    createGreeting("🍃 Enjoying the late summer breeze with a captivating story."),
    createGreeting("🗓️ August: Savoring the final stretch of summer anime."),
    createGreeting("🌻 Sun-drenched days and thrilling anime plots."),
    createGreeting("✨ August magic, one episode at a time."),
    createGreeting("🚀 Launching into new anime before fall semester hits!"),
    createGreeting("📚 Stocking up on essential anime for the academic year."),
    createGreeting("🌱 Witnessing the harvest of great summer seasonals."),
    createGreeting("📈 Making the most of remaining summer watch time."),
    createGreeting("💡 Bright new stories for golden August afternoons."),
    createGreeting("🥳 Celebrating the end of summer with a binge-fest!"),
    createGreeting("💖 Feel the bittersweet joy of summer's end with anime."),
    createGreeting("🌟 August nights are perfect for reflecting on favorite series."),
    createGreeting("🌌 Explore new dimensions before fall sets in."),
    createGreeting("🌬️ Catching the gentle breeze of lingering summer anime."),
    createGreeting("☕ Keeping cool with chilled beverages and captivating plots."),
    createGreeting("🖥️ Your ultimate late-summer anime command center."),
    createGreeting("📆 August: a month of transitions and thrilling twists."),
    createGreeting("📈 What captivating stories will August unveil?"),
    createGreeting("💡 Illuminating your evenings with compelling character arcs."),
    createGreeting("😎 Enjoying the summer warmth and stunning animation."),
    createGreeting("🌸 Adorn your screen with brilliant anime visuals."),
    createGreeting("🚀 Prepare for exciting lead-ups to fall releases!"),
    createGreeting("📚 Deep dive into rich narratives and complex themes."),
    createGreeting("🌱 Every episode is a journey through a vibrant world."),
    createGreeting("🎁 A little treat of animation for your mental well-being."),
    createGreeting("🕯️ Adding a soft glow to your relaxing viewing sessions."),
    createGreeting("🗺️ Navigating the ever-evolving anime landscape."),
    createGreeting("🧭 Setting a course for new narrative discoveries."),
    createGreeting("🎇 A month of sparkling content and emotional depth."),
    createGreeting("🗓️ August: the canvas for your next great anime memory."),
    createGreeting("🌊 Splashing into refreshing new anime experiences."),
    createGreeting("🌟 Let anime fill your summer days with wonder and excitement."),
    createGreeting("📚 Expanding your appreciation for diverse storytelling."),
    createGreeting("☕ The perfect blend of relaxation and thrilling action."),
    createGreeting("🖥️ The ultimate gateway to summer entertainment."),
    createGreeting("📈 Achieving new personal bests on your watchlist."),
    createGreeting("💡 Unleash your creativity with imaginative anime concepts."),
    createGreeting("🥳 Every new series is a cause for celebration!"),
    createGreeting("💖 Discovering new ships and OTPs this month."),
    createGreeting("✨ The magic of a well-told story resonates."),
    createGreeting("🌟 A dazzling array of shows awaits your undivided attention."),
    createGreeting("📚 Immerse yourself in intricate backstories and lore."),
    createGreeting("💨 Riding the wave of anticipation for upcoming hits."),
    createGreeting("🗓️ The start of something fantastic this August."),
    createGreeting("🎬 Get ready for some visually stunning anime premieres!"),
    createGreeting("🎮 Embark on thrilling quests from your favorite seat."),
    createGreeting("📝 Documenting your thoughts on current favorites."),
    createGreeting("🌱 Nurturing your inner otaku with quality content."),
    createGreeting("🎁 The endless joy of finding that perfect series."),
    createGreeting("🕯️ Crafting the ideal atmosphere for a deep dive."),
    createGreeting("🗺️ Traverse vast fictional worlds with ease and joy."),
  ],
  // September (Approx. 60 greetings)
  [
    createGreeting("🍁 Fall anime season is just around the corner!"),
    createGreeting("📚 Crisp air, cozy blanket, and a great anime. Perfect."),
    createGreeting("🍂 Golden leaves, golden anime moments."),
    createGreeting("🍎 As autumn arrives, so do new captivating stories."),
    createGreeting("🏫 Back to school, back to new anime schedules!"),
    createGreeting("☕ Trading iced coffee for warm lattes and seasonal anime."),
    createGreeting("🗓️ September: The start of a new anime season!"),
    createGreeting("🎃 Getting ready for cozy nights and thrilling plots."),
    createGreeting("✨ September magic, one episode at a time."),
    createGreeting("🚀 Launching into a fresh batch of fall anime!"),
    createGreeting("📚 Unpacking new stories for the new season."),
    createGreeting("🌱 Witnessing the changing colors, and changing anime trends."),
    createGreeting("📈 Falling into a rhythm of consistent anime watching."),
    createGreeting("💡 Bright new concepts to keep you warm indoors."),
    createGreeting("🥳 Celebrate the arrival of fall anime!"),
    createGreeting("💖 Feel the gentle embrace of autumn with a heartwarming series."),
    createGreeting("🌟 September nights are perfect for stargazing and screen time."),
    createGreeting("🌌 Explore new dimensions as nature prepares for winter."),
    createGreeting("🌬️ Catching the crisp breeze of fresh anime content."),
    createGreeting("🖥️ Your ultimate fall anime command center."),
    createGreeting("📆 September: a month of transitions and thrilling twists."),
    createGreeting("📈 What captivating stories will September unveil?"),
    createGreeting("💡 Illuminating your evenings with compelling character arcs."),
    createGreeting("🍂 Enjoying the autumn colors and stunning animation."),
    createGreeting("🌸 Adorn your screen with brilliant anime visuals."),
    createGreeting("🚀 Prepare for an exhilarating fall season!"),
    createGreeting("📚 Deep dive into rich narratives and complex themes."),
    createGreeting("🌱 Every episode is a journey through a vibrant world."),
    createGreeting("🎁 A little treat of animation for your mental well-being."),
    createGreeting("🕯️ Adding a soft glow to your relaxing viewing sessions."),
    createGreeting("🗺️ Navigating the ever-evolving anime landscape."),
    createGreeting("🧭 Setting a course for new narrative discoveries."),
    createGreeting("🎇 A month of sparkling content and emotional depth."),
    createGreeting("🗓️ September: the canvas for your next great anime memory."),
    createGreeting("🍁 Embracing the cozy vibes with some fantastic anime."),
    createGreeting("🌟 Let anime fill your autumn days with wonder and excitement."),
    createGreeting("📚 Expanding your appreciation for diverse storytelling."),
    createGreeting("☕ The perfect blend of autumn relaxation and thrilling action."),
    createGreeting("🖥️ The ultimate gateway to fall entertainment."),
    createGreeting("📈 Achieving new personal bests on your watchlist."),
    createGreeting("💡 Unleash your creativity with imaginative anime concepts."),
    createGreeting("🥳 Every new series is a cause for celebration!"),
    createGreeting("💖 Discovering new ships and OTPs this month."),
    createGreeting("✨ The magic of a well-told story resonates."),
    createGreeting("🌟 A dazzling array of shows awaits your undivided attention."),
    createGreeting("📚 Immerse yourself in intricate backstories and lore."),
    createGreeting("💨 Riding the wave of anticipation for upcoming hits."),
    createGreeting("🗓️ The start of something fantastic this September."),
    createGreeting("🎬 Get ready for some visually stunning anime premieres!"),
    createGreeting("🎮 Embark on thrilling quests from your favorite seat."),
    createGreeting("📝 Documenting your thoughts on current favorites."),
    createGreeting("🌱 Nurturing your inner otaku with quality content."),
    createGreeting("🎁 The endless joy of finding that perfect series."),
    createGreeting("🕯️ Crafting the ideal atmosphere for a deep dive."),
    createGreeting("🗺️ Traverse vast fictional worlds with ease and joy."),
  ],
  // October (Approx. 60 greetings)
  [
    createGreeting("🧛 It's spooky season! Time for something thrilling."),
    createGreeting("🧙 October is the perfect time for a mystery or horror anime."),
    createGreeting("👻 Embrace the eerie, or just enjoy some heartwarming slice-of-life."),
    createGreeting("🌕 Full moon, full watchlist."),
    createGreeting("🎃 Happy Halloween! Prepare for scares and delights."),
    createGreeting("🕷️ Cobwebs and captivating anime plots."),
    createGreeting("🗓️ October: The month of chills, thrills, and anime!"),
    createGreeting("🍬 Trick or treat yourself to a new binge!"),
    createGreeting("✨ October magic, one episode at a time."),
    createGreeting("🚀 Launching into spooky anime marathons!"),
    createGreeting("📚 Unearthing dark fantasies and psychological horrors."),
    createGreeting("🌱 Witnessing character transformations under a dark sky."),
    createGreeting("📈 Making chilling progress on your watchlist."),
    createGreeting("💡 Bright ideas for your next October binge."),
    createGreeting("🥳 Celebrate Halloween season with your favorite genres!"),
    createGreeting("💖 Feel the eerie thrill of October anime releases."),
    createGreeting("🌟 October nights are perfect for mysterious adventures."),
    createGreeting("🌌 Explore dark dimensions and haunted realms."),
    createGreeting("🌬️ Catching the spooky breeze of fresh anime content."),
    createGreeting("☕ Warm drinks and even warmer blankets for scary shows."),
    createGreeting("🖥️ Your ultimate Halloween anime command center."),
    createGreeting("📆 October: a month of supernatural stories and thrilling twists."),
    createGreeting("📈 What terrifying tales will October unveil?"),
    createGreeting("💡 Illuminating your evenings with spine-tingling plots."),
    createGreeting("👻 Enjoying the spooky vibes and stunning animation."),
    createGreeting("🌸 Adorn your screen with hauntingly beautiful anime visuals."),
    createGreeting("🚀 Prepare for an exhilarating Halloween season!"),
    createGreeting("📚 Deep dive into psychological narratives and complex themes."),
    createGreeting("🌱 Every episode is a journey into a shadowy world."),
    createGreeting("🎁 A little treat of animation for your adventurous spirit."),
    createGreeting("🕯️ Adding a soft glow to your chilling viewing sessions."),
    createGreeting("🗺️ Navigating the ever-evolving anime landscape."),
    createGreeting("🧭 Setting a course for new narrative discoveries."),
    createGreeting("🎇 A month of explosive content and emotional depth."),
    createGreeting("🗓️ October: the canvas for your next great anime memory."),
    createGreeting("🍁 Embracing the cozy vibes with some fantastic anime."),
    createGreeting("🌟 Let anime fill your autumn days with wonder and excitement."),
    createGreeting("📚 Expanding your appreciation for diverse storytelling."),
    createGreeting("☕ The perfect blend of autumn relaxation and thrilling action."),
    createGreeting("🖥️ The ultimate gateway to fall entertainment."),
    createGreeting("📈 Achieving new personal bests on your watchlist."),
    createGreeting("💡 Unleash your creativity with imaginative anime concepts."),
    createGreeting("🥳 Every new series is a cause for celebration!"),
    createGreeting("💖 Discovering new ships and OTPs this month."),
    createGreeting("✨ The magic of a well-told story resonates."),
    createGreeting("🌟 A dazzling array of shows awaits your undivided attention."),
    createGreeting("📚 Immerse yourself in intricate backstories and lore."),
    createGreeting("💨 Riding the wave of anticipation for upcoming hits."),
    createGreeting("🗓️ The start of something fantastic this October."),
    createGreeting("🎬 Get ready for some visually stunning anime premieres!"),
    createGreeting("🎮 Embark on thrilling quests from your favorite seat."),
    createGreeting("📝 Documenting your thoughts on current favorites."),
    createGreeting("🌱 Nurturing your inner otaku with quality content."),
    createGreeting("🎁 The endless joy of finding that perfect series."),
    createGreeting("🕯️ Crafting the ideal atmosphere for a deep dive."),
    createGreeting("🗺️ Traverse vast fictional worlds with ease and joy."),
  ],
  // November (Approx. 60 greetings)
  [
    createGreeting("🧣 Getting cozy for fall with some classic comfort shows."),
    createGreeting("☕ The countdown to the end of the year has begun. Time to finish those series!"),
    createGreeting("🍂 As the days shorten, the stories deepen."),
    createGreeting("🌬️ Brisk air, hot tea, and captivating anime."),
    createGreeting("🗓️ November: The month for reflection and powerful narratives."),
    createGreeting("🥧 Warm food, warm heart, warm anime!"),
    createGreeting("✨ November magic, one episode at a time."),
    createGreeting("🚀 Launching into end-of-year anime binges!"),
    createGreeting("📚 Unpacking emotional dramas and compelling mysteries."),
    createGreeting("🌱 Witnessing growth even as nature goes dormant."),
    createGreeting("📈 Making significant progress on your anime goals."),
    createGreeting("💡 Bright ideas for your next November binge."),
    createGreeting("🥳 Celebrate your anime achievements this month!"),
    createGreeting("💖 Feel the rich emotional depth of November anime."),
    createGreeting("🌟 November nights are perfect for introspective journeys."),
    createGreeting("🌌 Explore new dimensions under the fading autumn light."),
    createGreeting("🌬️ Catching the crisp breeze of deep anime narratives."),
    createGreeting("☕ Keeping warm with hot beverages and captivating plots."),
    createGreeting("🖥️ Your ultimate late-autumn anime command center."),
    createGreeting("📆 November: a month of heartfelt stories and profound twists."),
    createGreeting("📈 What compelling stories will November unveil?"),
    createGreeting("💡 Illuminating your evenings with thought-provoking character arcs."),
    createGreeting("🍂 Enjoying the late autumn colors and stunning animation."),
    createGreeting("🌸 Adorn your screen with brilliant anime visuals."),
    createGreeting("🚀 Prepare for exciting lead-ups to winter releases!"),
    createGreeting("📚 Deep dive into rich narratives and complex themes."),
    createGreeting("🌱 Every episode is a journey through a vibrant world."),
    createGreeting("🎁 A little treat of animation for your mental well-being."),
    createGreeting("🕯️ Adding a soft glow to your relaxing viewing sessions."),
    createGreeting("🗺️ Navigating the ever-evolving anime landscape."),
    createGreeting("🧭 Setting a course for new narrative discoveries."),
    createGreeting("🎇 A month of sparkling content and emotional depth."),
    createGreeting("🗓️ November: the canvas for your next great anime memory."),
    createGreeting("🍁 Embracing the cozy vibes with some fantastic anime."),
    createGreeting("🌟 Let anime fill your autumn days with wonder and excitement."),
    createGreeting("📚 Expanding your appreciation for diverse storytelling."),
    createGreeting("☕ The perfect blend of autumn relaxation and thrilling action."),
    createGreeting("🖥️ The ultimate gateway to fall entertainment."),
    createGreeting("📈 Achieving new personal bests on your watchlist."),
    createGreeting("💡 Unleash your creativity with imaginative anime concepts."),
    createGreeting("🥳 Every new series is a cause for celebration!"),
    createGreeting("💖 Discovering new ships and OTPs this month."),
    createGreeting("✨ The magic of a well-told story resonates."),
    createGreeting("🌟 A dazzling array of shows awaits your undivided attention."),
    createGreeting("📚 Immerse yourself in intricate backstories and lore."),
    createGreeting("💨 Riding the wave of anticipation for upcoming hits."),
    createGreeting("🗓️ The start of something fantastic this November."),
    createGreeting("🎬 Get ready for some visually stunning anime premieres!"),
    createGreeting("🎮 Embark on thrilling quests from your favorite seat."),
    createGreeting("📝 Documenting your thoughts on current favorites."),
    createGreeting("🌱 Nurturing your inner otaku with quality content."),
    createGreeting("🎁 The endless joy of finding that perfect series."),
    createGreeting("🕯️ Crafting the ideal atmosphere for a deep dive."),
    createGreeting("🗺️ Traverse vast fictional worlds with ease and joy."),
  ],
  // December (Approx. 60 greetings)
  [
    createGreeting("❄️ 'Tis the season for holiday specials and anime marathons."),
    createGreeting("🎇 Wrapping up the year with some unforgettable stories."),
    createGreeting("☃️ Get festive with your favorite characters."),
    createGreeting("🎄 Cozy up and dive into winter wonders."),
    createGreeting("🎁 Unwrap new episodes and discover hidden gems."),
    createGreeting("🗓️ December: The grand finale of your anime year!"),
    createGreeting("🥂 Toasting to all the incredible shows you watched."),
    createGreeting("✨ December magic, one episode at a time."),
    createGreeting("🚀 Launching into festive anime binges!"),
    createGreeting("📚 Reflecting on the year's best anime discoveries."),
    createGreeting("🌱 Witnessing the culmination of epic arcs."),
    createGreeting("📈 Finishing the year strong with your watchlist goals."),
    createGreeting("💡 Bright ideas for next year's anime lineup."),
    createGreeting("🥳 Celebrate the holidays with anime cheer!"),
    createGreeting("💖 Feel the heartwarming joy of holiday anime."),
    createGreeting("🌟 December nights are perfect for nostalgic re-watches."),
    createGreeting("🌌 Explore new dimensions under the festive lights."),
    createGreeting("🌬️ Catching the crisp breeze of winter anime stories."),
    createGreeting("☕ Keeping warm with hot cocoa and captivating plots."),
    createGreeting("🖥️ Your ultimate holiday anime command center."),
    createGreeting("📆 December: a month of reflection and thrilling twists."),
    createGreeting("📈 What captivating stories will December unveil?"),
    createGreeting("💡 Illuminating your evenings with compelling character arcs."),
    createGreeting("☃️ Enjoying the winter wonderland and stunning animation."),
    createGreeting("🌸 Adorn your screen with brilliant anime visuals."),
    createGreeting("🚀 Prepare for an exhilarating new year of anime!"),
    createGreeting("📚 Deep dive into rich narratives and complex themes."),
    createGreeting("🌱 Every episode is a journey through a vibrant world."),
    createGreeting("🎁 A little treat of animation for your mental well-being."),
    createGreeting("🕯️ Adding a soft glow to your relaxing viewing sessions."),
    createGreeting("🗺️ Navigating the ever-evolving anime landscape."),
    createGreeting("🧭 Setting a course for new narrative discoveries."),
    createGreeting("🎇 A month of sparkling content and emotional depth."),
    createGreeting("🗓️ December: the canvas for your next great anime memory."),
    createGreeting("❄️ Embracing the cozy vibes with some fantastic anime."),
    createGreeting("🌟 Let anime fill your winter days with wonder and excitement."),
    createGreeting("📚 Expanding your appreciation for diverse storytelling."),
    createGreeting("☕ The perfect blend of winter relaxation and thrilling action."),
    createGreeting("🖥️ The ultimate gateway to winter entertainment."),
    createGreeting("📈 Achieving new personal bests on your watchlist."),
    createGreeting("💡 Unleash your creativity with imaginative anime concepts."),
    createGreeting("🥳 Every new series is a cause for celebration!"),
    createGreeting("💖 Discovering new ships and OTPs this month."),
    createGreeting("✨ The magic of a well-told story resonates."),
    createGreeting("🌟 A dazzling array of shows awaits your undivided attention."),
    createGreeting("📚 Immerse yourself in intricate backstories and lore."),
    createGreeting("💨 Riding the wave of anticipation for upcoming hits."),
    createGreeting("🗓️ The start of something fantastic this December."),
    createGreeting("🎬 Get ready for some visually stunning anime premieres!"),
    createGreeting("🎮 Embark on thrilling quests from your favorite seat."),
    createGreeting("📝 Documenting your thoughts on current favorites."),
    createGreeting("🌱 Nurturing your inner otaku with quality content."),
    createGreeting("🎁 The endless joy of finding that perfect series."),
    createGreeting("🕯️ Crafting the ideal atmosphere for a deep dive."),
    createGreeting("🗺️ Traverse vast fictional worlds with ease and joy."),
  ],
];

const days: Greeting[][] = [
  // Sunday (Approx. 10 greetings)
  [
    createGreeting("😌 Hope you're having a relaxing Sunday."),
    createGreeting("🛋️ A lazy Sunday is perfect for catching up on episodes."),
    createGreeting("🧘‍♀️ Unwind and recharge with your current binge."),
    createGreeting("📺 Sunday Funday: Anime edition!"),
    createGreeting("☕ Starting your Sunday slowly with a captivating plot."),
    createGreeting("✨ Make this Sunday a truly anime-filled one."),
    createGreeting("📚 Diving into a new series on your day off."),
    createGreeting("😴 Recovering from the week with some well-deserved screen time."),
    createGreeting("🛌 Blanket forts and anime marathons – Sunday essentials."),
    createGreeting("🎮 Level up your relaxation this Sunday."),
  ],
  // Monday (Approx. 10 greetings)
  [
    createGreeting("☕ Let's beat the Monday blues with a great episode."),
    createGreeting("💪 Starting the week off right with some anime."),
    createGreeting("🚀 Blast off into a new week, fueled by anime."),
    createGreeting("🗓️ Monday: A fresh start and new anime goals!"),
    createGreeting("💼 Conquering the work week, one episode at a time."),
    createGreeting("💡 Spark your Monday with some brilliant animation."),
    createGreeting("📈 Get ready to achieve some anime progress!"),
    createGreeting("🤔 What new challenge will your heroes face this week?"),
    createGreeting("✨ Bring some magic to your Monday with a good show."),
    createGreeting("🌅 A new dawn, a new anime adventure."),
  ],
  // Tuesday (Approx. 10 greetings)
  [
    createGreeting("🌮 Tackle your Tuesday with an amazing story."),
    createGreeting("✨ Hope your week is off to a great start."),
    createGreeting("💡 Mid-week motivation starts with a compelling plot."),
    createGreeting("🗓️ Two days down, anime to go!"),
    createGreeting("📚 Diving deeper into your current obsession."),
    createGreeting("☕ A perfect Tuesday evening: hot drink, cool anime."),
    createGreeting("💖 Finding joy in the little anime moments."),
    createGreeting("🚀 Keep the momentum going with a thrilling episode."),
    createGreeting("🤔 What mysteries will Tuesday reveal in your show?"),
    createGreeting("🎮 Power through your tasks and treat yourself to anime."),
  ],
  // Wednesday (Approx. 10 greetings)
  [
    createGreeting("🐪 It's hump day! Time for a mid-week anime break."),
    createGreeting("🍿 Over the hump and into a new episode."),
    createGreeting("🌟 You're halfway there! Treat yourself to some screen time."),
    createGreeting("🗓️ Wednesday: The peak of the week, just like your favorite anime climax!"),
    createGreeting("☕ Halfway to the weekend, halfway through that series?"),
    createGreeting("✨ Inject some magic into your Wednesday."),
    createGreeting("📚 Unraveling complex plots with a mid-week watch."),
    createGreeting("💖 A little self-care with your favorite characters."),
    createGreeting("🚀 Propel yourself towards the weekend with an epic watch."),
    createGreeting("🎮 Ready for a mid-week boss battle (or just a new episode)?"),
  ],
  // Thursday (Approx. 10 greetings)
  [
    createGreeting("🎉 The weekend is almost here! What are you watching to celebrate?"),
    createGreeting("👍 Just one more day! Let's get through it with some anime."),
    createGreeting("🗓️ The finish line of the work week is in sight!"),
    createGreeting("🥳 Almost there! Time for some pre-weekend anime excitement."),
    createGreeting("💡 Brighten your Thursday with a fantastic episode."),
    createGreeting("📚 Getting ready for that weekend binge-read (or watch!)."),
    createGreeting("☕ Powering through to Friday with a captivating series."),
    createGreeting("💖 Feel the anticipation build, both for the weekend and your show."),
    createGreeting("🚀 Launching into early weekend vibes with anime."),
    createGreeting("🤔 What cliffhanger will keep you on the edge until tomorrow?"),
  ],
  // Friday (Approx. 10 greetings)
  [
    createGreeting("🙌 It's Friday! The perfect night for an anime marathon."),
    createGreeting("🎬 Weekend plans: anime, anime, and more anime."),
    createGreeting("🥳 Freedom! Time to dive deep into your watch list."),
    createGreeting("🗓️ TGIF! Thank Goodness It's Anime Friday!"),
    createGreeting("🍕 Pizza and anime: The ultimate Friday night combo."),
    createGreeting("✨ Let the weekend anime magic begin!"),
    createGreeting("📚 Unlocking new stories for your well-deserved break."),
    createGreeting("☕ Kick back, relax, and get lost in a new world."),
    createGreeting("💖 Embrace the joy of unlimited screen time."),
    createGreeting("🚀 Your weekend anime mission, should you choose to accept it."),
  ],
  // Saturday (Approx. 10 greetings)
  [
    createGreeting("🥳 It's Saturday! Let the binge-watching commence."),
    createGreeting("📺 Making the most of the weekend with some great shows."),
    createGreeting("🎮 Level up your weekend with non-stop anime."),
    createGreeting("🗓️ Saturday: Your personal anime holiday!"),
    createGreeting("🍿 Popcorn ready, remote in hand, anime on screen."),
    createGreeting("✨ A whole day dedicated to your favorite characters."),
    createGreeting("📚 Catching up on all those long-awaited episodes."),
    createGreeting("☕ The perfect day for a leisurely watch session."),
    createGreeting("💖 Cherish these moments of animated bliss."),
    createGreeting("🚀 Embark on an epic journey from dawn till dusk."),
  ],
];

const timeOfDay: Record<string, Greeting[]> = {
  morning: [
    createGreeting("🌅 Good morning! A fresh start for a new anime adventure."),
    createGreeting("☕ Rise and shine! What masterpiece will you watch today?"),
    createGreeting("🍳 Breakfast and anime – the perfect combo!"),
    createGreeting("☀️ The sun is up, and so is your potential watchlist."),
    createGreeting("📖 Begin your day with a captivating story."),
    createGreeting("✨ Waking up to a world of animated possibilities."),
    createGreeting("🗓️ Another day, another chance to find a new favorite."),
    createGreeting("🚀 Kickstart your morning with some high-energy action!"),
    createGreeting("💖 Sending good vibes for your morning anime session."),
    createGreeting("📚 Fuel your mind with inspiring narratives."),
  ],
  afternoon: [
    createGreeting("🌇 Good afternoon! Time for a midday anime break."),
    createGreeting("🥪 What's on your plate (and screen) this afternoon?"),
    createGreeting("🌞 Enjoy the afternoon with a thrilling episode."),
    createGreeting("📚 A perfect time to catch up before evening adventures."),
    createGreeting("🚶‍♂️ Wind down after a busy morning with some visual storytelling."),
    createGreeting("✨ Afternoon delight: your current anime obsession."),
    createGreeting("🗓️ Midday motivation, anime style!"),
    createGreeting("🚀 Keep your energy up with a captivating plot twist."),
    createGreeting("💖 A little animated escapism for your afternoon."),
    createGreeting("☕ Enjoying a relaxing watch before the evening rush."),
  ],
  evening: [
    createGreeting("🌃 Good evening! Unwind with some captivating anime."),
    createGreeting("🍽️ Dinner's done, now for the main event: your watchlist!"),
    createGreeting("🌙 The perfect time for a deep dive into a new series."),
    createGreeting("⭐ Stargazing and anime, a match made in heaven."),
    createGreeting("🎬 Settle in, the evening's entertainment begins now."),
    createGreeting("✨ Evening enchantment: your favorite anime moments."),
    createGreeting("🗓️ Winding down the day with epic tales."),
    createGreeting("🚀 Blast off into emotional new arcs."),
    createGreeting("💖 End your day with heartwarming or thrilling stories."),
    createGreeting("☕ The perfect accompaniment for your nightly binge."),
  ],
  night: [
    createGreeting("😴 Good night! Sweet dreams of your favorite characters."),
    createGreeting("🦉 The night owl's favorite pastime: late-night anime."),
    createGreeting("🌌 The stars are out, and so is your perfect winding-down show."),
    createGreeting("💤 Time to chill out with a relaxing episode before bed."),
    createGreeting("🕯️ A quiet night calls for a reflective or calming anime."),
    createGreeting("✨ Nighttime magic for your screen."),
    createGreeting("🗓️ One last episode before you drift off to sleep."),
    createGreeting("🚀 Exploring dreamscapes and fantastical worlds."),
    createGreeting("💖 A peaceful end to your day, filled with animated comfort."),
    createGreeting("☕ Your late-night companion for storytelling."),
  ],
};

const generic: Greeting[] = [
  createGreeting("🗺️ What adventures await in your watchlist today?"),
  createGreeting("🌌 Time to get lost in another world."),
  createGreeting("📜 Let's see what epic story unfolds today."),
  createGreeting("🚀 Ready to continue the journey?"),
  createGreeting("☀️ A new day, a new episode."),
  createGreeting("🖱️ Your next favorite story is just a click away."),
  createGreeting("🤩 Hope you find something amazing to watch today."),
  createGreeting("🍿 Let the binge-watching session begin!"),
  createGreeting("🪐 Discovering new worlds, one episode at a time."),
  createGreeting("🤔 What are we watching today?"),
  createGreeting("💥 Let's get back to the action."),
  createGreeting("🎌 The world of anime awaits your return."),
  createGreeting("✨ May your day be filled with unexpected plot twists."),
  createGreeting("👾 Press start on your next anime quest."),
  createGreeting("🎶 Tune into your favorite opening theme and dive in!"),
  createGreeting("📖 Every episode is a new chapter."),
  createGreeting("🎯 Target acquired: Your next binge-worthy series."),
  createGreeting("🌿 Take a moment, enjoy a story."),
  createGreeting("🎨 Immerse yourself in breathtaking animation."),
  createGreeting("💭 Dreaming of new anime worlds? Why not visit one today?"),
  createGreeting("🌟 Your ultimate guide to anime excellence."),
  createGreeting("🎬 The show must go on!"),
  createGreeting("💖 Find joy in every frame."),
  createGreeting("📚 Expanding your anime knowledge, one show at a time."),
  createGreeting("🎮 Level up your viewing experience."),
  createGreeting("📝 Documenting your epic watch history."),
  createGreeting("🌈 A spectrum of emotions, all in one place."),
  createGreeting("💡 Spark your imagination with incredible stories."),
  createGreeting("🌌 Journey beyond the stars, or just to the next episode."),
  createGreeting("🚀 Propel yourself into new narratives."),
  createGreeting("🎉 Celebrate every discovery, big or small."),
  createGreeting("🥳 Time for some well-deserved entertainment."),
  createGreeting("☕ Enjoying a moment of animated bliss."),
  createGreeting("🖥️ Your screen is a portal to endless worlds."),
  createGreeting("📈 Always striving for the next great watch."),
  createGreeting("💨 Catching up on the latest hype."),
  createGreeting("🗓️ Keeping track of your anime adventures."),
  createGreeting("🧭 Navigating the vast ocean of anime."),
  createGreeting("🎇 A burst of creativity, right at your fingertips."),
  createGreeting("🌱 Cultivating a superb watchlist."),
  createGreeting("🎁 The gift of escapism, whenever you need it."),
  createGreeting("🕯️ Creating the perfect atmosphere for your viewing."),
  createGreeting("🗺️ Plotting your next anime conquest."),
  createGreeting("✨ Unleash your inner otaku!"),
  createGreeting("🌟 Shine bright with every new episode."),
  createGreeting("📚 Learning new lessons from fictional heroes."),
  createGreeting("🎮 Embark on a new quest today!"),
];

const getRandomItem = (arr: Greeting[]): Greeting => arr[Math.floor(Math.random() * arr.length)];

export const getGreetingPhrase = (): string => {
  const now = new Date();
  const month = now.getMonth(); // 0-11
  const dayOfMonth = now.getDate();
  const dayOfWeek = now.getDay(); // 0-6 (Sun-Sat)
  const hour = now.getHours(); // 0-23

  const potentialGreetings: Greeting[] = [];

  // 1. Holiday-specific greetings (Highest Priority)
  const holidayKey = `${String(month + 1).padStart(2, '0')}-${String(dayOfMonth).padStart(2, '0')}`;
  if (holidays[holidayKey]) {
    potentialGreetings.push(...holidays[holidayKey]);
  }
  // Thanksgiving (4th Thursday in November)
  if (month === 10) { // November is month 10
      const year = now.getFullYear();
      const firstDayOfMonth = new Date(year, 10, 1).getDay(); // Day of week for Nov 1st
      // Calculate the date of the first Thursday
      const firstThursday = 1 + (4 - firstDayOfMonth + 7) % 7;
      // The fourth Thursday will be 3 weeks after the first Thursday
      const fourthThursday = firstThursday + 3 * 7;
      if (dayOfMonth === fourthThursday && holidays['11-4-4']) {
          potentialGreetings.push(...holidays['11-4-4']);
      }
  }

  // 2. Month-specific greetings
  potentialGreetings.push(...months[month]);

  // 3. Day-of-week specific greetings
  potentialGreetings.push(...days[dayOfWeek]);

  // 4. Time-of-day specific greetings
  if (hour >= 5 && hour < 12) { // 5:00 - 11:59
    potentialGreetings.push(...timeOfDay.morning);
  } else if (hour >= 12 && hour < 18) { // 12:00 - 17:59
    potentialGreetings.push(...timeOfDay.afternoon);
  } else if (hour >= 18 && hour < 22) { // 18:00 - 21:59
    potentialGreetings.push(...timeOfDay.evening);
  } else { // 22:00 - 4:59
    potentialGreetings.push(...timeOfDay.night);
  }

  // Combine all specific greetings for the current context
  const allContextualGreetings = [...potentialGreetings];

  // Filter out recently used greetings from the contextual pool
  let availableContextual = allContextualGreetings.filter(g => !isGreetingRecentlyUsed(g.id));
  
  // Also filter generic greetings
  let availableGeneric = generic.filter(g => !isGreetingRecentlyUsed(g.id));

  let selectedGreeting: Greeting;

  if (availableContextual.length > 0) {
    // Prefer contextual greetings if available
    selectedGreeting = getRandomItem(availableContextual);
  } else if (availableGeneric.length > 0) {
    // Fallback to available generic greetings if no unique contextual ones
    selectedGreeting = getRandomItem(availableGeneric);
  } else {
    // Ultimate fallback: if all contextual AND all generic greetings have been recently used,
    // we must pick from the unfiltered pool. Prioritize contextual if any exist, otherwise any generic.
    // This is highly unlikely with a decent size of greetings and a cache of 20.
    if (allContextualGreetings.length > 0) {
      selectedGreeting = getRandomItem(allContextualGreetings);
    } else {
      selectedGreeting = getRandomItem(generic);
    }
    console.warn("All relevant and generic greetings have been recently used. Repeating a greeting.");
  }

  // Add the selected greeting's ID to the cache
  addUsedGreeting(selectedGreeting.id);

  return selectedGreeting.text;
};